# CMAKE generated file: DO NOT EDIT!
# Generated by "Unix Makefiles" Generator, CMake Version 3.10

# Default target executed when no arguments are given to make.
default_target: all

.PHONY : default_target

# Allow only one "make -f Makefile2" at a time, but pass parallelism.
.NOTPARALLEL:


#=============================================================================
# Special targets provided by cmake.

# Disable implicit rules so canonical targets will work.
.SUFFIXES:


# Remove some rules from gmake that .SUFFIXES does not remove.
SUFFIXES =

.SUFFIXES: .hpux_make_needs_suffix_list


# Suppress display of executed commands.
$(VERBOSE).SILENT:


# A target that is always out of date.
cmake_force:

.PHONY : cmake_force

#=============================================================================
# Set environment variables for the build.

# The shell in which to execute make rules.
SHELL = /bin/sh

# The CMake executable.
CMAKE_COMMAND = /usr/bin/cmake

# The command to remove a file.
RM = /usr/bin/cmake -E remove -f

# Escaping for special characters.
EQUALS = =

# The top-level source directory on which CMake was run.
CMAKE_SOURCE_DIR = /home/ubuntu-nico/Documents/Workspace/Projet_C/Codage_de_Huffman

# The top-level build directory on which CMake was run.
CMAKE_BINARY_DIR = /home/ubuntu-nico/Documents/Workspace/Projet_C/Codage_de_Huffman

#=============================================================================
# Targets provided globally by CMake.

# Special rule for the target rebuild_cache
rebuild_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake to regenerate build system..."
	/usr/bin/cmake -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : rebuild_cache

# Special rule for the target rebuild_cache
rebuild_cache/fast: rebuild_cache

.PHONY : rebuild_cache/fast

# Special rule for the target edit_cache
edit_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "No interactive CMake dialog available..."
	/usr/bin/cmake -E echo No\ interactive\ CMake\ dialog\ available.
.PHONY : edit_cache

# Special rule for the target edit_cache
edit_cache/fast: edit_cache

.PHONY : edit_cache/fast

# The main all target
all: cmake_check_build_system
	$(CMAKE_COMMAND) -E cmake_progress_start /home/ubuntu-nico/Documents/Workspace/Projet_C/Codage_de_Huffman/CMakeFiles /home/ubuntu-nico/Documents/Workspace/Projet_C/Codage_de_Huffman/CMakeFiles/progress.marks
	$(MAKE) -f CMakeFiles/Makefile2 all
	$(CMAKE_COMMAND) -E cmake_progress_start /home/ubuntu-nico/Documents/Workspace/Projet_C/Codage_de_Huffman/CMakeFiles 0
.PHONY : all

# The main clean target
clean:
	$(MAKE) -f CMakeFiles/Makefile2 clean
.PHONY : clean

# The main clean target
clean/fast: clean

.PHONY : clean/fast

# Prepare targets for installation.
preinstall: all
	$(MAKE) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall

# Prepare targets for installation.
preinstall/fast:
	$(MAKE) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall/fast

# clear depends
depend:
	$(CMAKE_COMMAND) -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 1
.PHONY : depend

#=============================================================================
# Target rules for targets named Codage_de_Huffman

# Build rule for target.
Codage_de_Huffman: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 Codage_de_Huffman
.PHONY : Codage_de_Huffman

# fast build rule for target.
Codage_de_Huffman/fast:
	$(MAKE) -f CMakeFiles/Codage_de_Huffman.dir/build.make CMakeFiles/Codage_de_Huffman.dir/build
.PHONY : Codage_de_Huffman/fast

arbre.o: arbre.c.o

.PHONY : arbre.o

# target to build an object file
arbre.c.o:
	$(MAKE) -f CMakeFiles/Codage_de_Huffman.dir/build.make CMakeFiles/Codage_de_Huffman.dir/arbre.c.o
.PHONY : arbre.c.o

arbre.i: arbre.c.i

.PHONY : arbre.i

# target to preprocess a source file
arbre.c.i:
	$(MAKE) -f CMakeFiles/Codage_de_Huffman.dir/build.make CMakeFiles/Codage_de_Huffman.dir/arbre.c.i
.PHONY : arbre.c.i

arbre.s: arbre.c.s

.PHONY : arbre.s

# target to generate assembly for a file
arbre.c.s:
	$(MAKE) -f CMakeFiles/Codage_de_Huffman.dir/build.make CMakeFiles/Codage_de_Huffman.dir/arbre.c.s
.PHONY : arbre.c.s

couple.o: couple.c.o

.PHONY : couple.o

# target to build an object file
couple.c.o:
	$(MAKE) -f CMakeFiles/Codage_de_Huffman.dir/build.make CMakeFiles/Codage_de_Huffman.dir/couple.c.o
.PHONY : couple.c.o

couple.i: couple.c.i

.PHONY : couple.i

# target to preprocess a source file
couple.c.i:
	$(MAKE) -f CMakeFiles/Codage_de_Huffman.dir/build.make CMakeFiles/Codage_de_Huffman.dir/couple.c.i
.PHONY : couple.c.i

couple.s: couple.c.s

.PHONY : couple.s

# target to generate assembly for a file
couple.c.s:
	$(MAKE) -f CMakeFiles/Codage_de_Huffman.dir/build.make CMakeFiles/Codage_de_Huffman.dir/couple.c.s
.PHONY : couple.c.s

heapq.o: heapq.c.o

.PHONY : heapq.o

# target to build an object file
heapq.c.o:
	$(MAKE) -f CMakeFiles/Codage_de_Huffman.dir/build.make CMakeFiles/Codage_de_Huffman.dir/heapq.c.o
.PHONY : heapq.c.o

heapq.i: heapq.c.i

.PHONY : heapq.i

# target to preprocess a source file
heapq.c.i:
	$(MAKE) -f CMakeFiles/Codage_de_Huffman.dir/build.make CMakeFiles/Codage_de_Huffman.dir/heapq.c.i
.PHONY : heapq.c.i

heapq.s: heapq.c.s

.PHONY : heapq.s

# target to generate assembly for a file
heapq.c.s:
	$(MAKE) -f CMakeFiles/Codage_de_Huffman.dir/build.make CMakeFiles/Codage_de_Huffman.dir/heapq.c.s
.PHONY : heapq.c.s

huffman.o: huffman.c.o

.PHONY : huffman.o

# target to build an object file
huffman.c.o:
	$(MAKE) -f CMakeFiles/Codage_de_Huffman.dir/build.make CMakeFiles/Codage_de_Huffman.dir/huffman.c.o
.PHONY : huffman.c.o

huffman.i: huffman.c.i

.PHONY : huffman.i

# target to preprocess a source file
huffman.c.i:
	$(MAKE) -f CMakeFiles/Codage_de_Huffman.dir/build.make CMakeFiles/Codage_de_Huffman.dir/huffman.c.i
.PHONY : huffman.c.i

huffman.s: huffman.c.s

.PHONY : huffman.s

# target to generate assembly for a file
huffman.c.s:
	$(MAKE) -f CMakeFiles/Codage_de_Huffman.dir/build.make CMakeFiles/Codage_de_Huffman.dir/huffman.c.s
.PHONY : huffman.c.s

main.o: main.c.o

.PHONY : main.o

# target to build an object file
main.c.o:
	$(MAKE) -f CMakeFiles/Codage_de_Huffman.dir/build.make CMakeFiles/Codage_de_Huffman.dir/main.c.o
.PHONY : main.c.o

main.i: main.c.i

.PHONY : main.i

# target to preprocess a source file
main.c.i:
	$(MAKE) -f CMakeFiles/Codage_de_Huffman.dir/build.make CMakeFiles/Codage_de_Huffman.dir/main.c.i
.PHONY : main.c.i

main.s: main.c.s

.PHONY : main.s

# target to generate assembly for a file
main.c.s:
	$(MAKE) -f CMakeFiles/Codage_de_Huffman.dir/build.make CMakeFiles/Codage_de_Huffman.dir/main.c.s
.PHONY : main.c.s

# Help Target
help:
	@echo "The following are some of the valid targets for this Makefile:"
	@echo "... all (the default if no target is provided)"
	@echo "... clean"
	@echo "... depend"
	@echo "... rebuild_cache"
	@echo "... Codage_de_Huffman"
	@echo "... edit_cache"
	@echo "... arbre.o"
	@echo "... arbre.i"
	@echo "... arbre.s"
	@echo "... couple.o"
	@echo "... couple.i"
	@echo "... couple.s"
	@echo "... heapq.o"
	@echo "... heapq.i"
	@echo "... heapq.s"
	@echo "... huffman.o"
	@echo "... huffman.i"
	@echo "... huffman.s"
	@echo "... main.o"
	@echo "... main.i"
	@echo "... main.s"
.PHONY : help



#=============================================================================
# Special targets to cleanup operation of make.

# Special rule to run CMake to check the build system integrity.
# No rule that depends on this can have commands that come from listfiles
# because they might be regenerated.
cmake_check_build_system:
	$(CMAKE_COMMAND) -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 0
.PHONY : cmake_check_build_system

